export const catsData = [
    {
      emotionTags: ["malhumorado"],
      isGif: false,
      image: "malhumorado.jpeg",
      alt: "A cat looking malhumorado",
    },
    {
      emotionTags: ["malhumorado", "insomnio"],
      isGif: false,
      image: "malhumorado2.jpeg",
      alt: "A cat looking malhumorado",
    },
    {
      emotionTags: ["malhumorado"],
      isGif: false,
      image: "malhumorado3.jpeg",
      alt: "A cat looking malhumorado",
    },
    {
      emotionTags: ["confundido", "triste"],
      isGif: false,
      image: "confundido.jpeg",
      alt: "A cat looking confundido",
    },
    {
      emotionTags: ["dominante", "malhumorado"],
      isGif: false,
      image: "dominante.jpeg",
      alt: "A cat looking dominante",
    },
    {
      emotionTags: ["feliz", "relajado"],
      isGif: false,
      image: "feliz.jpeg",
      alt: "A cat looking feliz",
    },
    {
      emotionTags: ["hambriento"],
      isGif: false,
      image: "hambriento.jpeg",
      alt: "A cat looking hambriento",
    },
    {
      emotionTags: ["hambriento"],
      isGif: false,
      image: "hambriento1.jpeg",
      alt: "A cat looking hambriento",
    },
    {
      emotionTags: ["insomnio"],
      isGif: false,
      image: "insomnio.jpeg",
      alt: "A cat looking insomnio",
    },
    {
      emotionTags: ["insomnio"],
      isGif: false,
      image: "insomnio1.jpeg",
      alt: "A cat looking insomnio",
    },
    {
      emotionTags: ["relajado"],
      isGif: false,
      image: "flojo.jpeg",
      alt: "A cat looking lazy",
    },
    {
      emotionTags: ["asustado"],
      isGif: false,
      image: "nervioso.jpeg",
      alt: "A cat looking nervioso",
    },
    {
      emotionTags: ["triste"],
      isGif: false,
      image: "triste.jpeg",
      alt: "A cat looking triste",
    },
    {
      emotionTags: ["triste", "malhumorado"],
      isGif: false,
      image: "triste1.jpeg",
      alt: "A cat looking triste",
    },
    {
      emotionTags: ["malhumorado"],
      isGif: true,
      image: "malhumorado.gif",
      alt: "A cat looking malhumorado",
    },
    {
      emotionTags: ["malhumorado"],
      isGif: true,
      image: "malhumorado2.gif",
      alt: "A cat looking angry",
    },
    {
      emotionTags: ["confundido"],
      isGif: true,
      image: "confundido2.gif",
      alt: "A cat looking confundido",
    },
    {
      emotionTags: ["dominante"],
      isGif: true,
      image: "dominante.gif",
      alt: "A cat looking dominante",
    },
    {
      emotionTags: ["feliz"],
      isGif: true,
      image: "feliz.gif",
      alt: "A cat looking feliz",
    },
    {
      emotionTags: ["hambriento", "triste", "confundido"],
      isGif: true,
      image: "confundido.gif",
      alt: "A cat looking hambriento",
    },
    {
      emotionTags: ["hambriento"],
      isGif: true,
      image: "hambriento.gif",
      alt: "A cat looking hambriento",
    },
    {
      emotionTags: ["hambriento"],
      isGif: true,
      image: "hambriento2.gif",
      alt: "A cat looking hambriento",
    },
    {
      emotionTags: ["insomnio", "asustado"],
      isGif: true,
      image: "insomnio2.gif",
      alt: "A cat looking insomnio",
    },
    {
      emotionTags: ["relajado"],
      isGif: true,
      image: "flojo.gif",
      alt: "A cat looking relajado",
    },
    {
      emotionTags: ["relajado"],
      isGif: true,
      image: "relajado2.gif",
      alt: "A cat looking relajado",
    },
    {
      emotionTags: ["asustado", "triste"],
      isGif: true,
      image: "nervioso.gif",
      alt: "A cat looking nervioso",
    },
    {
      emotionTags: ["asustado"],
      isGif: true,
      image: "nervioso2.gif",
      alt: "A cat looking asustado",
    },
    {
      emotionTags: ["triste"],
      isGif: true,
      image: "triste.gif",
      alt: "A cat looking triste",
    },
  ];